name: Distribute source to pypi package
on:
  pull_request:
    branches:
      - main

jobs:
  distribute-fastapi-fastkit-package-bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
