name: release package to github
on:
  pull_request:
    branches:
      - main

jobs:
  release-fastapi-fastkit-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
